org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.installations.auto-detect=true

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47.2,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=playwrightforkubejs
mod_name=Playwright For KubeJS
mod_license=MIT
mod_version=0.1.0
mod_group_id=com.playwrightforkubejs
mod_authors=Playwright For KubeJS
mod_description=Playwright automation bridge for KubeJS.

kubejs_version=2001.6.5-build.26
rhino_version=2001.2.2-build.17
architectury_version=9.2.14
